[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day1"

[[bin]]
name = "day1_const"

[[bin]]
name = "day2"

[dependencies]
color-eyre = "0.6.2"
winnow = "0.5.19"
